### ISSUE TITLE
Movie page - When we try to share the movie on Pinterest, we get an error

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#102]
The URL also appears wrong as displayed in the url tab in the above image
You can use the below test acct
pratstest8@gmail.com
temp123
![343](https://cloud.githubusercontent.com/assets/3326712/6749472/9c30d4a6-cf16-11e4-9374-fc467472534c.png)

![543](https://cloud.githubusercontent.com/assets/3326712/6747440/55a3f8b8-ceff-11e4-8c2a-7dd5cb6dc105.png)

Expected:

![5](https://cloud.githubusercontent.com/assets/3326712/6749421/1ba299b4-cf16-11e4-827e-d4c19af76737.png)
![1243](https://cloud.githubusercontent.com/assets/3326712/6749443/4d12738e-cf16-11e4-8d87-7a250add70ce.png)
![43245](https://cloud.githubusercontent.com/assets/3326712/6749447/5e4d76a8-cf16-11e4-938b-5852c8805fc2.png)

**Comment by SurekhaRane** [comment]
This feature has not been implemented yet.
