### ISSUE TITLE
Movie Page - The lower part of the video hides below the screen.

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#103]
Actual view on the full width of the screen
![rr](https://cloud.githubusercontent.com/assets/3326712/6750060/8d59b94c-cf1c-11e4-909b-4c2757837925.png)

Below part of the video is not displayed when we are viewing the video
![43244](https://cloud.githubusercontent.com/assets/3326712/6750194/de87f468-cf1d-11e4-82b1-e22f50815c4d.png)

**Comment by jeromie** [comment]
@pratsajency if I reduce the height of the video, vertical black space appears on both sides of the video as the video width also reduces proportionately. If this black space is present on the sides of the video, the next/prev arrows cannot be seen.

I have now added playback controls for the video which also has full screen option, so the user can click on this if he wants to view the video without any part getting cut.

**Comment by anujkhurana** [comment]
Please do not work on the video/image displayed on the single video page. I
will provide inputs.
