### ISSUE TITLE
Movie Page - Provide option for Playback with timeline

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#104]
Currently User has no other option than Play and Pause while viewing a Video.

![2](https://cloud.githubusercontent.com/assets/3326712/6750736/81fc8b72-cf23-11e4-8e2c-19d193e31c68.png)

**Comment by anujkhurana** [comment]
We are only embedding youtube video no? Not sure I understood. Is there a
youtube feature that is not working on our website?

**Comment by jeromie** [comment]
Yes, the youtube playback controls currently dont appear on the site.

On Fri, Mar 20, 2015 at 5:56 PM, anujkhurana <notifications@github.com>
wrote:

> We are only embedding youtube video no? Not sure I understood. Is there a
> youtube feature that is not working on our website?
>
> On Fri, Mar 20, 2015 at 5:08 PM, Pratiksha <notifications@github.com>
> wrote:
>
> > Currently User has no other option than Play and Pause while viewing a
> > Video.
> >
> > [image: 2]
> > <
> https://cloud.githubusercontent.com/assets/3326712/6750736/81fc8b72-cf23-11e4-8e2c-19d193e31c68.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ajency/short-film-window/issues/104>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ajency/short-film-window/issues/104#issuecomment-84002934>
> .
>



-- 
Regards,
Jeromie Fernandes
