### ISSUE TITLE
Footer - The text inside the "Newsletter" input field should display text as in psd

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#18]
The text on the psd says "Subscribe to Our Newsletter to know about latest movies and articles"

![ddw](https://cloud.githubusercontent.com/assets/3326712/6251558/90cdf170-b7ba-11e4-9ccf-510db6715ba8.png)
![wef](https://cloud.githubusercontent.com/assets/3326712/6251557/90c399a0-b7ba-11e4-9c0a-57f5e3d87af1.png)

**Comment by pratsajency** [comment]
@jeromie 
Is it not possible to display the complete text ""Subscribe to Our Newsletter to know about latest movies and articles"?

**Comment by anujkhurana** [comment]
5 columns. on a 1000 px screen each column gets 200 px. 200 px fitting that
amount of text with a subscribe label next to it. Do you think it is
possible?

Please be reasonable and see what you are asking for. Don't want
unnecessary tasks being created for team.
