### ISSUE TITLE
Homepage - The "in focus" navigation/search/date/like/views should aligned and formatted similar to psd

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#20]
Expected:
1. Search view  same as psd
2. Navigation placed besides the images
3. Comma between day and year
4. Like icon placed after link count
5. Views icon placed after view count 

![435](https://cloud.githubusercontent.com/assets/3326712/6251785/ec1084f2-b7bb-11e4-9a8a-b4c01ead9ea2.png)
![2232](https://cloud.githubusercontent.com/assets/3326712/6251787/ec7cb6b8-b7bb-11e4-982b-da4eb40c75ad.png)

**Comment by jeromie** [comment]
@pratsajency see below responses:
1. The search box has a hamburger icon as well. Whats the significance of this? Does the search box have some more functionality?
2. The navigation arrows are placed at the vertical center of the slider. For 'In Focus' section, the text is also part of the slider, thereby increasing the height and hence the arrows are slightly below the image. I could keep the arrows a fixed distance from the top of the image so it appears as per the psd, but this would affect the placement of the arrows on other sliders. Kindly advise.
3. Done.
4. Done.
5. Done.

**Comment by anujkhurana** [comment]
Let's do the slider arrows as in the design. I think that does look better
(and maybe might work better too) than in the center. We could do different
classes for slider? One where the arrows are fixed distance from top and
other where they are venter aligned?

**Comment by jeromie** [comment]
Added a class to move the arrows a fixed distance from the top of the slider instead of vertical center.

**Comment by pratsajency** [comment]
@jeromie 
On pt#1, will get the feedback from client.

**Comment by pratsajency** [comment]
@jeromie 
We can ignore the "menu" icon on the Search box.
