### ISSUE TITLE
The site font should be same as the psd font

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#21]
![jlkj](https://cloud.githubusercontent.com/assets/3326712/6251858/67ac91b4-b7bc-11e4-98f1-2d68c22a171e.png)
![jlk](https://cloud.githubusercontent.com/assets/3326712/6251857/66ef2b10-b7bc-11e4-9ad8-fceaf19b7eee.png)

@jeromie 
Let me know if you do not have the font details, will get it from the client.

**Comment by jeromie** [comment]
@pratsajency will check the psd for fonts used.
@anujkhurana please fwd the psds to kiran.

**Comment by pratsajency** [comment]
Feedback from client on the Font - 

Please check with the fonts and sizes. I don't know DIN is a hard font to find online. There are some web safe alternatives here.
http://www.google.com/fonts/
http://graphicdesign.stackexchange.com/questions/7178/is-there-a-din-font-free-alternative.

**Comment by jeromie** [comment]
Font changed to Roboto as mentioned in mail.
