### ISSUE TITLE
Playlists - The font/headers should be styled to be in sync with the Homepage

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#236]
http://www.shortfilmwindow.com/playlist/play6/

**Comment by renukaajency** [comment]
Done

**Comment by pratsajency** [comment]
@renukaajency 

Format the "New and Noteworthy" to match the Homepage

Playlist View
![sc](https://cloud.githubusercontent.com/assets/3326712/7852173/fac9b18c-0516-11e5-9d12-e35251050314.png)

Homepage View
![lk](https://cloud.githubusercontent.com/assets/3326712/7852174/ff4f2318-0516-11e5-8494-1a58a25e7898.png)
