### ISSUE TITLE
Playlists - The "View" and "Like" count needs to be aligned

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#237]
![32rt](https://cloud.githubusercontent.com/assets/3326712/7782314/74582f66-012e-11e5-8a41-7f6e9f068719.png)

**Comment by renukaajency** [comment]
@nivedita-k can you check why there's a lot of space after the number '0'? Its not being trimmed in the code side I think. The spacing in CSS is the same for all, if I change them then rest of the numbers will look un-aligned. Its only one or two of the numbers/counts that have excess space after them. I don't know where its being called from.

![capture](https://cloud.githubusercontent.com/assets/11813307/7797919/692bd7ee-0310-11e5-9a43-464c1bac8793.PNG)

**Comment by nivedita-k** [comment]
resolved

**Comment by anujkhurana** [comment]
Please do not close any ticket that has been opened by pratiksha. She will
verify and close it.
