### ISSUE TITLE
iPhone/iPad Movies Page - The Images under "Similar Movies" section should be responsive

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#241]
http://mobiletest.me/iphone_5_emulator/#u=http://www.shortfilmwindow.com/you-there/
http://mobiletest.me/ipad_mini_emulator/#u=http://www.shortfilmwindow.com/you-there/

![wg](https://cloud.githubusercontent.com/assets/3326712/7782468/31969f60-0137-11e5-9e34-7c13f2aa4ea9.png)

**Comment by renukaajency** [comment]
Done
