### ISSUE TITLE
Page Contents - Provide padding around images adding in Page/Post contents

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#245]
![fw](https://cloud.githubusercontent.com/assets/3326712/7783527/04538a1e-0163-11e5-8a10-5613ffa7ddbb.png)

![f09](https://cloud.githubusercontent.com/assets/3326712/7783547/6ec40374-0163-11e5-92ae-c0929e7f7170.png)

**Comment by renukaajency** [comment]
Done

**Comment by pratsajency** [comment]
@renukaajency 

The images view on Mobiles yet needs to be fixed. 

![o](https://cloud.githubusercontent.com/assets/3326712/7851991/cb011118-0514-11e5-9cb5-d74bbab8e8b1.png)
![f3](https://cloud.githubusercontent.com/assets/3326712/7851992/cb0c07d0-0514-11e5-9664-dda1bc65040d.png)
