### ISSUE TITLE
Homepage - "Explore by Genre" section images should be square

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#248]
![egwgw](https://cloud.githubusercontent.com/assets/3326712/7795172/e5cc812a-02ef-11e5-875b-29dd22ee67d0.png)

**Comment by anujkhurana** [comment]
Why should images be square?

**Comment by pratsajency** [comment]
Client's request in the mail sent today.

**Comment by renukaajency** [comment]
Done
