### ISSUE TITLE
Header Menu - Display the Main Menu items as per the "Main Menu" list

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#250]
![eg](https://cloud.githubusercontent.com/assets/3326712/7795511/7924c2ea-02f3-11e5-90c1-d44db7e3720b.png)
![42t](https://cloud.githubusercontent.com/assets/3326712/7795512/7a360fea-02f3-11e5-830d-a0286800c362.png)

**Comment by renukaajency** [comment]
Done
