### ISSUE TITLE
Live Site - Homepage - The images appear blur on "In focus" section, although the uploaded images were of high resolution

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#258]
![uhj](https://cloud.githubusercontent.com/assets/3326712/7863319/4ae07eaa-0579-11e5-8a36-e36ed3669f28.png)

**Comment by renukaajency** [comment]
@nivedita-k Are the thumbnails regenerated? Actual image sizes are that of ordinary WP thumbnails - 150 x 150px. Want me to do it?

**Comment by anujkhurana** [comment]
I am guessing we have not configured image sizes in new site.
