### ISSUE TITLE
Search - The search box should display a "searching lens" inside the box as shown in the psd 

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#46]
![6555](https://cloud.githubusercontent.com/assets/3326712/6438436/f1f27448-c0ee-11e4-810b-9b143a6ccde0.png)
![652](https://cloud.githubusercontent.com/assets/3326712/6438437/f1ff406a-c0ee-11e4-9233-d146c127f595.png)

**Comment by jeromie** [comment]
search lens added. Search text also needs to be there as some text is needed as placeholder in order to display an icon.
