### ISSUE TITLE
Mobile View - Reformat the grids and sliders on mobile view  

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#47]
![6554](https://cloud.githubusercontent.com/assets/3326712/6438596/c02565ea-c0f0-11e4-8318-f0efc7b497ac.png)
![9565](https://cloud.githubusercontent.com/assets/3326712/6438597/c078e832-c0f0-11e4-9215-b4d7792e8258.png)

Client has provided some suggestions, images placed here
https://drive.google.com/a/ajency.in/folderview?id=0B1VZYXFX0g0BWFpuT2xpbXNKVHc&usp=drive_web

**Comment by jeromie** [comment]
@pratsajency the sliders have been made responsive. The grids are already responsive.
