### ISSUE TITLE
Homepage - Add more details to the Grid as shown in the psd 

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#6]
![222](https://cloud.githubusercontent.com/assets/3326712/6214283/4f7a906e-b61d-11e4-9beb-8fa42aa3fe10.png)
![111](https://cloud.githubusercontent.com/assets/3326712/6214284/4fb11ce2-b61d-11e4-933c-de233539670a.png)

**Comment by anujkhurana** [comment]
Also the margin between grid elements seems to be on the higher side. Could
we try reducing that to the level in the design?

**Comment by jeromie** [comment]
Yes, can be reduced. Currently maintained as bootstrap padding value between columns. Will reduce to match the design.
