### ISSUE TITLE
Template required for "Contact Us" and "FAQ" page

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#60]
Currently assigning the default template to a page, displays contents as shown below.
Also page contents are not displayed.
![134](https://cloud.githubusercontent.com/assets/3326712/6665152/4884defa-cbfc-11e4-847f-2631047cb88b.png)

Expected:
![42](https://cloud.githubusercontent.com/assets/3326712/6665173/6543c736-cbfc-11e4-8736-38d15d8e706b.png)

**Comment by jeromie** [comment]
default template fixed. Content can be added from dashboard of default template pages.
