### ISSUE TITLE
Movie Page - No video is been displayed on http://www.shortfilmwindow.com/traffic/

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#96]

**Comment by pratsajency** [comment]
@SurekhaRane 
Now none of the videos are playing.
Kindly fix this soon.

**Comment by SurekhaRane** [comment]
Page takes time to load. So after the page has loaded, videos work fine.

We can have a loader on the page indicating that page is still loading.

**Comment by anujkhurana** [comment]
Please dont spent any time on this. The whole approach to loading and
playing videos is not something i am comfortable with. I will let you know
what needs to be done here.
