### ISSUE TITLE
Exploer Grid - Clicking on any Movie on the grid should open that movie in a new tab

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#98]
![983](https://cloud.githubusercontent.com/assets/3326712/6746858/95cc4756-cef5-11e4-92c5-dcee203621a6.png)

**Comment by anujkhurana** [comment]
Client has asked for it? Why open in new tab?

**Comment by pratsajency** [comment]
Right now, the links don't open at all on Explore Grid.

And mentioned as "new tab", as that's how its behaving on Explore List and Couch.

**Comment by anujkhurana** [comment]
Let's not open new tabs for any links on the site. If the link is offsite
(takes user away from shortfilmwindow) then we can do new tab.
