### ISSUE TITLE
Movie Page - Clicking on the FB Share the link and data displayed is wrong

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#99]
![34](https://cloud.githubusercontent.com/assets/3326712/6747321/97f7b6e8-cefd-11e4-9ccc-4af92cfbb1f4.png)
![24](https://cloud.githubusercontent.com/assets/3326712/6747322/9870c04c-cefd-11e4-8df0-735378656b6f.png)

**Comment by SurekhaRane** [comment]
This feature has not been implemented yet.
